# The URL the site will be built for
base_url = "https://uutils.github.io"

title = "uutils"

description = ""

default_language = "en"

generate_feeds = true

[markdown]
highlight_code = true
highlight_theme = "OneHalfLight"
